Repository TEN-framework/ten-framework, pull requests merged in 2024-07, with the labels that each got.

#35 fix(): adjust interrupt logic
  agents/addon/extension/interrupt_detector/extension.go
Labels: enhancement

#40 New banner image
  README-CN.md
  README.md
  images/logo_banner_dark.png
  images/logo_banner_ref_line_light.png
Labels: documentation, UI UX

#45 Upgrade build image
  .devcontainer/devcontainer.json
  .gitignore
  README-CN.md
  README.md
  agents/addon/extension/azure_tts/src/tts.cc
  agents/scripts/install_deps_and_build.sh
Labels: enhancement

#48 Bugfix/logo
  playground/package.json
  playground/src/app/favicon.ico
  playground/src/app/layout.tsx
  playground/src/assets/logo.png
  playground/src/assets/logo.svg
  playground/src/assets/logo_small.svg
  playground/src/components/header/index.tsx
  playground/src/components/icons/index.tsx
  playground/src/components/icons/logo/index.tsx
  playground/src/components/loginCard/index.tsx
  playground/src/components/logo/index.tsx
Labels: UI UX

#49 Feat tts elevenlabs
  agents/addon/extension/elevenlabs_tts/elevenlabs_tts.go
  agents/addon/extension/elevenlabs_tts/elevenlabs_tts_extension.go
  agents/addon/extension/elevenlabs_tts/go.mod
  agents/addon/extension/elevenlabs_tts/go.sum
  agents/addon/extension/elevenlabs_tts/manifest.json
  agents/addon/extension/elevenlabs_tts/property.json
Labels: Feature

#51 [Feature Request] Feat tts elevenlabs
  agents/addon/extension/elevenlabs_tts/elevenlabs_tts_extension.go
  agents/addon/extension/elevenlabs_tts/manifest.json
  agents/addon/extension/elevenlabs_tts/pcm.go
Labels: Feature

#47 Updating README-cn.md
  README-CN.md
  images/logo_banner.png
  images/wechat-qrcode.png
Labels: documentation

#54 Add git for devcontainer
  .devcontainer/devcontainer.json
Labels: enhancement

#58 Adding new README.md banner image
  README.md
  images/new-banner-without-tagline.png
Labels: documentation

#59 Update README-CN.md
  README-CN.md
Labels: documentation

#67 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#68 Create SECURITY.md
  SECURITY.md
Labels: documentation

#69 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#66 Update README.md
  README-CN.md
  README.md
  images/docker-setting.gif
Labels: documentation

#73 update wechat image
  images/wechat-qrcode.png
Labels: documentation

#74 Removing the style hack in README.md
  README.md
Labels: documentation

#79 Adding a new Discord link that sets never to expire
  README.md
Labels: documentation

#75 Changing agents server to latest
  README-CN.md
  README.md
Labels: documentation

#86 Bugfix/svg logo
  playground/src/assets/logo.png
  playground/src/assets/logo.svg
  playground/src/components/header/index.tsx
  playground/src/components/icons/index.tsx
  playground/src/components/icons/logo/index.tsx
  playground/src/components/icons/types.ts
  playground/src/components/loginCard/index.module.scss
  playground/src/components/loginCard/index.tsx
  playground/src/components/logo/index.tsx
Labels: UI UX

#96 Moving up star us section
  README.md
Labels: documentation

#99 Adding Arch docs
  README.md
  markdowns/astra-architecture.md
  markdowns/code-of-conduct/code-of-conduct.md
  markdowns/code-of-conduct/contributing.md
  markdowns/code-of-conduct/security.md
  markdowns/message-type-and-name-cn.md
  markdowns/message-type-and-name.md
  markdowns/readmes/README-CN.md
  markdowns/rte-api.md
  markdowns/rte-schema-cn.md
  markdowns/rte-schema.md
  markdowns/tutorials/extension-tutorial-cpp-cn.md
  markdowns/tutorials/extension-tutorial-cpp.md
  markdowns/tutorials/extension-tutorial-go-cn.md
  markdowns/tutorials/extension-tutorial-go.md
Labels: documentation

#102 Changing folder names from markdowns to docs
  README.md
  docs/astra-architecture.md
  docs/code-of-conduct/code-of-conduct.md
  docs/code-of-conduct/contributing.md
  docs/code-of-conduct/security.md
  docs/message-type-and-name-cn.md
  docs/message-type-and-name.md
  docs/readmes/README-CN.md
  docs/rte-api.md
  docs/rte-schema-cn.md
  docs/rte-schema.md
  docs/tutorials/extension-tutorial-cpp-cn.md
  docs/tutorials/extension-tutorial-cpp.md
  docs/tutorials/extension-tutorial-go-cn.md
  docs/tutorials/extension-tutorial-go.md
Labels: documentation

#130 fix(): update docker build command to include platform specification
  Makefile
Labels: documentation

#133 Update README.md - Rename manifest example
  README.md
Labels: documentation

#131 Updating sections as well as fixing WeChat QR Code
  docs/readmes/README-CN.md
Labels: documentation

#104 Restructure readme for better and easier use
  README.md
Labels: documentation
